# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 10:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secret',
            managers=[
                ('Secretmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
